name: Deploy to Lightsail

on:
  push:
    branches:
      - master  # or main if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO: https://github.com/Ashmit111/Task_Manager.git
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Lightsail via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -e
            if ! command -v git >/dev/null; then
              sudo apt-get update
              sudo apt-get install -y git curl
            fi
            if ! command -v node >/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null; then
              sudo npm install -g pm2 serve
            fi

            WORKDIR=/var/www/task_manager
            if [ ! -d "$WORKDIR" ]; then
              sudo mkdir -p "$WORKDIR"
              sudo chown -R $(whoami):$(whoami) "$WORKDIR"
              git clone https://github.com/Ashmit111/Task_Manager.git "$WORKDIR"
            fi

            cd "$WORKDIR"
            git fetch --all
            git reset --hard origin/master

            echo "PORT=8080" > "$WORKDIR/backend/.env"
            echo "MONGO_URI=$MONGO_URI" >> "$WORKDIR/backend/.env"

            cd "$WORKDIR/backend"
            npm install --production
            pm2 restart backend || pm2 start npm --name backend -- start

            cd "$WORKDIR/frontend"
            npm install --production
            npm run build
            pm2 restart frontend || pm2 serve ./dist 3000 --name frontend

            pm2 save
          EOF
